/*
Unleash API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 6.1.12+main
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetSamlSettings401Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSamlSettings401Response{}

// GetSamlSettings401Response struct for GetSamlSettings401Response
type GetSamlSettings401Response struct {
	// The ID of the error instance
	Id *string `json:"id,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
	// A description of what went wrong.
	Message              *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetSamlSettings401Response GetSamlSettings401Response

// NewGetSamlSettings401Response instantiates a new GetSamlSettings401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSamlSettings401Response() *GetSamlSettings401Response {
	this := GetSamlSettings401Response{}
	return &this
}

// NewGetSamlSettings401ResponseWithDefaults instantiates a new GetSamlSettings401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSamlSettings401ResponseWithDefaults() *GetSamlSettings401Response {
	this := GetSamlSettings401Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetSamlSettings401Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSamlSettings401Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetSamlSettings401Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetSamlSettings401Response) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetSamlSettings401Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSamlSettings401Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetSamlSettings401Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetSamlSettings401Response) SetName(v string) {
	o.Name = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetSamlSettings401Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSamlSettings401Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetSamlSettings401Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetSamlSettings401Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetSamlSettings401Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSamlSettings401Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSamlSettings401Response) UnmarshalJSON(data []byte) (err error) {
	varGetSamlSettings401Response := _GetSamlSettings401Response{}

	err = json.Unmarshal(data, &varGetSamlSettings401Response)

	if err != nil {
		return err
	}

	*o = GetSamlSettings401Response(varGetSamlSettings401Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSamlSettings401Response struct {
	value *GetSamlSettings401Response
	isSet bool
}

func (v NullableGetSamlSettings401Response) Get() *GetSamlSettings401Response {
	return v.value
}

func (v *NullableGetSamlSettings401Response) Set(val *GetSamlSettings401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSamlSettings401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSamlSettings401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSamlSettings401Response(val *GetSamlSettings401Response) *NullableGetSamlSettings401Response {
	return &NullableGetSamlSettings401Response{value: val, isSet: true}
}

func (v NullableGetSamlSettings401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSamlSettings401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
