/*
Unleash API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.4.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateGroupSchemaUsersInnerUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateGroupSchemaUsersInnerUser{}

// CreateGroupSchemaUsersInnerUser A minimal user object
type CreateGroupSchemaUsersInnerUser struct {
	// The user id
	Id                   int32 `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _CreateGroupSchemaUsersInnerUser CreateGroupSchemaUsersInnerUser

// NewCreateGroupSchemaUsersInnerUser instantiates a new CreateGroupSchemaUsersInnerUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGroupSchemaUsersInnerUser(id int32) *CreateGroupSchemaUsersInnerUser {
	this := CreateGroupSchemaUsersInnerUser{}
	this.Id = id
	return &this
}

// NewCreateGroupSchemaUsersInnerUserWithDefaults instantiates a new CreateGroupSchemaUsersInnerUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGroupSchemaUsersInnerUserWithDefaults() *CreateGroupSchemaUsersInnerUser {
	this := CreateGroupSchemaUsersInnerUser{}
	return &this
}

// GetId returns the Id field value
func (o *CreateGroupSchemaUsersInnerUser) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateGroupSchemaUsersInnerUser) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateGroupSchemaUsersInnerUser) SetId(v int32) {
	o.Id = v
}

func (o CreateGroupSchemaUsersInnerUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGroupSchemaUsersInnerUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateGroupSchemaUsersInnerUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateGroupSchemaUsersInnerUser := _CreateGroupSchemaUsersInnerUser{}

	err = json.Unmarshal(data, &varCreateGroupSchemaUsersInnerUser)

	if err != nil {
		return err
	}

	*o = CreateGroupSchemaUsersInnerUser(varCreateGroupSchemaUsersInnerUser)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateGroupSchemaUsersInnerUser struct {
	value *CreateGroupSchemaUsersInnerUser
	isSet bool
}

func (v NullableCreateGroupSchemaUsersInnerUser) Get() *CreateGroupSchemaUsersInnerUser {
	return v.value
}

func (v *NullableCreateGroupSchemaUsersInnerUser) Set(val *CreateGroupSchemaUsersInnerUser) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGroupSchemaUsersInnerUser) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGroupSchemaUsersInnerUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGroupSchemaUsersInnerUser(val *CreateGroupSchemaUsersInnerUser) *NullableCreateGroupSchemaUsersInnerUser {
	return &NullableCreateGroupSchemaUsersInnerUser{value: val, isSet: true}
}

func (v NullableCreateGroupSchemaUsersInnerUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGroupSchemaUsersInnerUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
