/*
Unleash API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5.2.0-main
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ChangeRequestCommentSchemaCreatedBy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeRequestCommentSchemaCreatedBy{}

// ChangeRequestCommentSchemaCreatedBy struct for ChangeRequestCommentSchemaCreatedBy
type ChangeRequestCommentSchemaCreatedBy struct {
	Username NullableString `json:"username,omitempty"`
	ImageUrl NullableString `json:"imageUrl,omitempty"`
}

// NewChangeRequestCommentSchemaCreatedBy instantiates a new ChangeRequestCommentSchemaCreatedBy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeRequestCommentSchemaCreatedBy() *ChangeRequestCommentSchemaCreatedBy {
	this := ChangeRequestCommentSchemaCreatedBy{}
	return &this
}

// NewChangeRequestCommentSchemaCreatedByWithDefaults instantiates a new ChangeRequestCommentSchemaCreatedBy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeRequestCommentSchemaCreatedByWithDefaults() *ChangeRequestCommentSchemaCreatedBy {
	this := ChangeRequestCommentSchemaCreatedBy{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChangeRequestCommentSchemaCreatedBy) GetUsername() string {
	if o == nil || IsNil(o.Username.Get()) {
		var ret string
		return ret
	}
	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChangeRequestCommentSchemaCreatedBy) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// HasUsername returns a boolean if a field has been set.
func (o *ChangeRequestCommentSchemaCreatedBy) HasUsername() bool {
	if o != nil && o.Username.IsSet() {
		return true
	}

	return false
}

// SetUsername gets a reference to the given NullableString and assigns it to the Username field.
func (o *ChangeRequestCommentSchemaCreatedBy) SetUsername(v string) {
	o.Username.Set(&v)
}

// SetUsernameNil sets the value for Username to be an explicit nil
func (o *ChangeRequestCommentSchemaCreatedBy) SetUsernameNil() {
	o.Username.Set(nil)
}

// UnsetUsername ensures that no value is present for Username, not even an explicit nil
func (o *ChangeRequestCommentSchemaCreatedBy) UnsetUsername() {
	o.Username.Unset()
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChangeRequestCommentSchemaCreatedBy) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ImageUrl.Get()
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChangeRequestCommentSchemaCreatedBy) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageUrl.Get(), o.ImageUrl.IsSet()
}

// HasImageUrl returns a boolean if a field has been set.
func (o *ChangeRequestCommentSchemaCreatedBy) HasImageUrl() bool {
	if o != nil && o.ImageUrl.IsSet() {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given NullableString and assigns it to the ImageUrl field.
func (o *ChangeRequestCommentSchemaCreatedBy) SetImageUrl(v string) {
	o.ImageUrl.Set(&v)
}

// SetImageUrlNil sets the value for ImageUrl to be an explicit nil
func (o *ChangeRequestCommentSchemaCreatedBy) SetImageUrlNil() {
	o.ImageUrl.Set(nil)
}

// UnsetImageUrl ensures that no value is present for ImageUrl, not even an explicit nil
func (o *ChangeRequestCommentSchemaCreatedBy) UnsetImageUrl() {
	o.ImageUrl.Unset()
}

func (o ChangeRequestCommentSchemaCreatedBy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeRequestCommentSchemaCreatedBy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Username.IsSet() {
		toSerialize["username"] = o.Username.Get()
	}
	if o.ImageUrl.IsSet() {
		toSerialize["imageUrl"] = o.ImageUrl.Get()
	}
	return toSerialize, nil
}

type NullableChangeRequestCommentSchemaCreatedBy struct {
	value *ChangeRequestCommentSchemaCreatedBy
	isSet bool
}

func (v NullableChangeRequestCommentSchemaCreatedBy) Get() *ChangeRequestCommentSchemaCreatedBy {
	return v.value
}

func (v *NullableChangeRequestCommentSchemaCreatedBy) Set(val *ChangeRequestCommentSchemaCreatedBy) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeRequestCommentSchemaCreatedBy) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeRequestCommentSchemaCreatedBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeRequestCommentSchemaCreatedBy(val *ChangeRequestCommentSchemaCreatedBy) *NullableChangeRequestCommentSchemaCreatedBy {
	return &NullableChangeRequestCommentSchemaCreatedBy{value: val, isSet: true}
}

func (v NullableChangeRequestCommentSchemaCreatedBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeRequestCommentSchemaCreatedBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
