/*
Unleash API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the AdminStrategiesSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminStrategiesSchema{}

// AdminStrategiesSchema A collection of strategies belonging to a specified segment.
type AdminStrategiesSchema struct {
	// The list of strategies
	Strategies []AdminStrategiesSchemaStrategiesInner `json:"strategies"`
}

// NewAdminStrategiesSchema instantiates a new AdminStrategiesSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminStrategiesSchema(strategies []AdminStrategiesSchemaStrategiesInner) *AdminStrategiesSchema {
	this := AdminStrategiesSchema{}
	this.Strategies = strategies
	return &this
}

// NewAdminStrategiesSchemaWithDefaults instantiates a new AdminStrategiesSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminStrategiesSchemaWithDefaults() *AdminStrategiesSchema {
	this := AdminStrategiesSchema{}
	return &this
}

// GetStrategies returns the Strategies field value
func (o *AdminStrategiesSchema) GetStrategies() []AdminStrategiesSchemaStrategiesInner {
	if o == nil {
		var ret []AdminStrategiesSchemaStrategiesInner
		return ret
	}

	return o.Strategies
}

// GetStrategiesOk returns a tuple with the Strategies field value
// and a boolean to check if the value has been set.
func (o *AdminStrategiesSchema) GetStrategiesOk() ([]AdminStrategiesSchemaStrategiesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Strategies, true
}

// SetStrategies sets field value
func (o *AdminStrategiesSchema) SetStrategies(v []AdminStrategiesSchemaStrategiesInner) {
	o.Strategies = v
}

func (o AdminStrategiesSchema) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminStrategiesSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["strategies"] = o.Strategies
	return toSerialize, nil
}

type NullableAdminStrategiesSchema struct {
	value *AdminStrategiesSchema
	isSet bool
}

func (v NullableAdminStrategiesSchema) Get() *AdminStrategiesSchema {
	return v.value
}

func (v *NullableAdminStrategiesSchema) Set(val *AdminStrategiesSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminStrategiesSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminStrategiesSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminStrategiesSchema(val *AdminStrategiesSchema) *NullableAdminStrategiesSchema {
	return &NullableAdminStrategiesSchema{value: val, isSet: true}
}

func (v NullableAdminStrategiesSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminStrategiesSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
