/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// How many applications have seen this feature toggle, as well as how this feature was evaluated the last hour
type FeatureUsageSchema struct {
	// The version of this schema
	Version int32 `json:"version"`
	// The maturity level of this API (alpha, beta, stable, deprecated)
	Maturity string `json:"maturity"`
	// The name of the feature
	FeatureName string `json:"featureName"`
	// Last hour statistics. Accumulated per feature per environment. Contains counts for evaluations to true (yes) and to false (no)
	LastHourUsage []FeatureEnvironmentMetricsSchema `json:"lastHourUsage"`
	// A list of applications seen using this feature
	SeenApplications []string `json:"seenApplications"`
}
