/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A definition of the project environment
type EnvironmentSchema struct {
	// The name of the environment
	Name string `json:"name"`
	// The [type of environment](https://docs.getunleash.io/reference/environments#environment-types).
	Type_ string `json:"type"`
	// `true` if the environment is enabled for the project, otherwise `false`.
	Enabled bool `json:"enabled"`
	// `true` if the environment is protected, otherwise `false`. A *protected* environment can not be deleted.
	Protected bool `json:"protected"`
	// Priority of the environment in a list of environments, the lower the value, the higher up in the list the environment will appear. Needs to be an integer
	SortOrder int32 `json:"sortOrder"`
	// The number of projects with this environment
	ProjectCount int32 `json:"projectCount,omitempty"`
	// The number of API tokens for the project environment
	ApiTokenCount int32 `json:"apiTokenCount,omitempty"`
	// The number of enabled toggles for the project environment
	EnabledToggleCount int32 `json:"enabledToggleCount,omitempty"`
}
