/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// A definition of the project used for projects listing purposes
type ProjectSchema struct {
	// The id of this project
	Id string `json:"id"`
	// The name of this project
	Name string `json:"name"`
	// Additional information about the project
	Description string `json:"description,omitempty"`
	// An indicator of the [project's health](https://docs.getunleash.io/reference/technical-debt#health-rating) on a scale from 0 to 100
	Health float64 `json:"health,omitempty"`
	// The number of features this project has
	FeatureCount float64 `json:"featureCount,omitempty"`
	// The number of members this project has
	MemberCount float64   `json:"memberCount,omitempty"`
	CreatedAt   time.Time `json:"createdAt,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt,omitempty"`
	// `true` if the project was favorited, otherwise `false`.
	Favorite bool `json:"favorite,omitempty"`
	// The project's [collaboration mode](https://docs.getunleash.io/reference/project-collaboration-mode). Determines whether non-project members can submit change requests or not.
	Mode string `json:"mode,omitempty"`
	// A default stickiness for the project affecting the default stickiness value for variants and Gradual Rollout strategy
	DefaultStickiness string `json:"defaultStickiness,omitempty"`
}
