/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Contains information about which settings are configured for version info collection and feature usage collection.
type TelemetrySettingsSchema struct {
	// Whether collection of version info is enabled/active.
	VersionInfoCollectionEnabled bool `json:"versionInfoCollectionEnabled"`
	// Whether collection of feature usage metrics is enabled/active.
	FeatureInfoCollectionEnabled bool `json:"featureInfoCollectionEnabled"`
}
