/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Used by service orchestrators to decide whether this Unleash instance should be marked as healthy or unhealthy
type HealthCheckSchema struct {
	// The state this Unleash instance is in. GOOD if everything is ok, BAD if the instance should be restarted
	Health string `json:"health"`
}
