/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// A report of the current health of the requested project, with datapoints like counters of currently active, stale, and potentially stale feature toggles.
type HealthReportSchema struct {
	// The project overview version.
	Version int32 `json:"version"`
	// The project's name
	Name string `json:"name"`
	// The project's description
	Description string `json:"description,omitempty"`
	// A default stickiness for the project affecting the default stickiness value for variants and Gradual Rollout strategy
	DefaultStickiness string `json:"defaultStickiness"`
	// The project's [collaboration mode](https://docs.getunleash.io/reference/project-collaboration-mode). Determines whether non-project members can submit change requests or not.
	Mode string `json:"mode"`
	// The number of users/members in the project.
	Members int32 `json:"members"`
	// The overall [health rating](https://docs.getunleash.io/reference/technical-debt#health-rating) of the project.
	Health int32 `json:"health"`
	// An array containing the names of all the environments configured for the project.
	Environments []ProjectEnvironmentSchema `json:"environments"`
	// An array containing an overview of all the features of the project and their individual status
	Features []FeatureSchema `json:"features"`
	// When the project was last updated.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// When the project was last updated.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Indicates if the project has been marked as a favorite by the current user requesting the project health overview.
	Favorite bool                `json:"favorite,omitempty"`
	Stats    *ProjectStatsSchema `json:"stats,omitempty"`
	// The number of potentially stale feature toggles.
	PotentiallyStaleCount float64 `json:"potentiallyStaleCount"`
	// The number of active feature toggles.
	ActiveCount float64 `json:"activeCount"`
	// The number of stale feature toggles.
	StaleCount float64 `json:"staleCount"`
}
