/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Holds all metrics gathered over a window of time. Typically 1 hour wide
type ClientMetricsSchemaBucket struct {
	Start *DateSchema `json:"start"`
	Stop  *DateSchema `json:"stop"`
	// an object containing feature names with yes/no plus variant usage
	Toggles map[string]ClientMetricsSchemaBucketToggles `json:"toggles"`
}
