/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A [feature toggle type](https://docs.getunleash.io/reference/feature-toggle-types).
type FeatureTypeSchema struct {
	// The identifier of this feature toggle type.
	Id string `json:"id"`
	// The display name of this feature toggle type.
	Name string `json:"name"`
	// A description of what this feature toggle type is intended to be used for.
	Description string `json:"description"`
	// How many days it takes before a feature toggle of this typed is flagged as [potentially stale](https://docs.getunleash.io/reference/technical-debt#stale-and-potentially-stale-toggles) by Unleash. If this value is `null`, Unleash will never mark it as potentially stale.
	LifetimeDays int32 `json:"lifetimeDays"`
}
