/*
 * Unleash API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.2.0-main
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A role holds permissions to allow Unleash to decide what actions a role holder is allowed to perform
type RoleSchema struct {
	// The role id
	Id int32 `json:"id"`
	// A role can either be a global role (applies to all projects) or a project role
	Type_ string `json:"type"`
	// The name of the role
	Name string `json:"name"`
	// A more detailed description of the role and what use it's intended for
	Description string `json:"description,omitempty"`
}
