name: build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # run validation against latest unleash-server image
    - cron: "30 5 * * 1-5"

permissions:
  packages: read

jobs:
  build:
    strategy:
      matrix:
        image: 
          - "ghcr.io/ivarconr/unleash-enterprise:5.5.6-terraform.0"
          - "unleashorg/unleash-server:latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Login to ghcr
        if: contains(matrix.image, 'unleash-enterprise')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gastonfournier
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Setup enterprise docker image
        if: contains(matrix.image, 'unleash-enterprise')
        run: |
          echo UNLEASH_DOCKER_IMAGE=${{ matrix.image }} >> $GITHUB_ENV
          echo UNLEASH_ENTERPRISE=true >> $GITHUB_ENV
      - name: Startup services ${{ matrix.image }}
        run: docker compose up -d --wait -t 60
      - name: Tests ${{ matrix.image }}
        run: go test -v -cover ./test/...
