name: build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # run validation against latest unleash-server image
    - cron: "30 5 * * 1-5"

permissions:
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNLEASH_DOCKER_IMAGE: ivarconr/unleash-enterprise:latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gastonfournier
          password: ${{ secrets.GHCR_TOKEN }}
      - run: docker pull ${UNLEASH_DOCKER_IMAGE}
      - name: Startup services
        run: docker compose up -d --wait -t 60
      - name: Tests
        run: go test ./...
        env:
          ENTERPRISE: "true"
