name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install dependencies
        run: go version
      - name: Build
        run: echo "Should we?"
      - name: Test
        run: go run main.go -unleash-api http://localhost:4242 -authorization *:*.unleash-insecure-admin-api-token
