name: build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # run validation against latest unleash-server image
    - cron: "30 5 * * 1-5"

permissions:
  packages: read

jobs:
  build:
    strategy:
      matrix:
        image: 
          - "ghcr.io/ivarconr/unleash-enterprise:latest"
          - "unleashorg/unleash-server:5.3.5"
          - "unleashorg/unleash-server:5.4.4"
          - "unleashorg/unleash-server:latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Login to ghcr
        if: startsWith(matrix.image, 'ghcr.io/ivarconr')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gastonfournier
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Setup enterprise docker image
        if: startsWith(matrix.image, 'ghcr.io/ivarconr')
        run: |
          echo UNLEASH_DOCKER_IMAGE=${{ secrets.ENTERPRISE_IMAGE }} >> $GITHUB_ENV
          echo ENTERPRISE=true >> $GITHUB_ENV
      - name: Startup services ${{ matrix.image }}
        run: docker compose up -d --wait -t 60
      - name: Tests ${{ matrix.image }}
        run: go test -v -cover ./test/...
